version: "2"

services:
  kafka-server:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka-server
    networks:
      - kafka-network
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092 | CONTROLLER://kafka-server:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - kafka-network
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=prsdhatamaCluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=//kafka-server:9092

networks:
  kafka-network:
    driver: bridge

volumes:
  kafka_data:
    driver: local



